before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: bharatkalluri
    name: harmony

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true

  prerelease: auto

  # You can disable this pipe in order to not upload any artifacts.
  # Defaults to false.
  disable: true